[package]
name = "ringvrf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zk-utils-test = { git = "https://github.com/prz23/zk-utils-test"}
curve25519-dalek = "2"
sha3 = "0.8"
polynomials = "0.2.4"